runtime: python27
api_version: 1
threadsafe: true
instance_class: B4
basic_scaling:
  max_instances: 2

builtins:
- deferred: on

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /.*
  script: mplus.app

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

libraries:
- name: numpy
  version: "1.6.1"
- name: jinja2
  version: latest